---
# tasks file for apache
- name: instalamos paquete
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_packages }}"

- name: levantamos el servicio
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: crea pagina de bienvenida
  copy:
    src: index.html
    dest: "/var/www/html/index.html"
    notify: "restart service httpd"

- name: copia template config
  template:
    src: template_ejemplo.j2
    dest: "/var/tmp/test2.conf"
    notify: "restart service httpd"
