---
# tasks file for apache
- name: instalamos paquete
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_packages }}"

- name: levantamos el servicio
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: crea pagina de bienvenida
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name: copia template config
  tempalte:
    src: template_ejemplo.j2
    dest: /var/www/html/test2.conf
    notify: "restart service httpd"
