---
- hosts: "{{ servidores }}"
  become: true
  gather_facts: false
  tasks:
  - name: validamos conexion web
    block:
      - name: comprobamos si la web responde
        uri:
          url: "http://localhost"
    rescue:
      - name: Asumo que el servicio httpd esta parado, por lo tanto lo levanto
        service:
          name: httpd
          state: started
    always:
      - name: La web responde?
        uri:
          url: "http://localhost"
      - name: Muestro un mensaje
        debug:
          msg: "funciono!!!"