---
- hosts: "{{ servidores }}" #variable para limitar los hosts
  become: true
  tasks:
  - name: crear un usuario
    user: 
      name: "{{ item }}"
      shell: "/bin/bash"
      comment: "usuario creado por Ansible"
      state: present
    with_items: 
    - Roberto
    - Alfonso
    - Cristina
    - Zoe
