---
- hosts: "{{ servidores }}"
  become: true
  tasks:
  - name: copiamos template
    template:
      src: /tools/git_repositories/ansible_calzagar/awx_labo_linux_carlos/template_ejemplo.j2
      dest: "/var/tmp/test2.conf"
      owner: root
      group: root
      mode: '0644'
  - name: copiamos fichero de config
    copy:
      src: /tools/git_repositories/ansible_calzagar/awx_labo_linux_carlos/test.conf
      dest: "/var/tmp/test.conf"
      owner: root
      group: root
      mode: '0644'