---
- hosts: "{{ servidores }}"
  become: true
  gather_facts: false
  tasks:
  - name: crear un usuario
    user: 
      name: "{{ item.nombre }}"
      groups: "{{ item.equipo }}"
      shell: "/bin/bash"
      comment: "usuario creado por Ansible"
      state: present
    with_items: "{{ usuarios }}"

